version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    labels: ["component/dependencies"]

  # Maintain dependencies for dashboard, shell, and packages
  - package-ecosystem: "npm"
    directories:
      - "/"
      - "/shell"
      - "/pkg/*"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    labels: ["component/dependencies"]
